### PR TITLE
Enable RAW image capture in Pro Mode

### PR DESCRIPTION
**Pull request by ShaDisNX255**
I think this should be enough to enable you to save RAW photos with the Pro mode (gotta activate in settings, check it out)

### CODE REVIEW

**Comment by UltraHQ** [comment]
Awesome find!
But unfortunately it is producing very broken results, so it is unusable on the A72.

**Comment by ShaDisNX255** [comment]
> Awesome find! But unfortunately it is producing very broken results, so it is unusable on the A72.

Is it taking the picture and breaking it up into colors? (4 I believe)
If this is the case, let me check what other lines it needs because I remember I also had this problem but then I added more lines to camera-feature that fixed it but I'm not exactly sure which one

**Comment by UltraHQ** [comment]
> > Awesome find! But unfortunately it is producing very broken results, so it is unusable on the A72.
> 
> Is it taking the picture and breaking it up into colors? (4 I believe) If this is the case, let me check what other lines it needs because I remember I also had this problem but then I added more lines to camera-feature that fixed it but I'm not exactly sure which one

Yes, it's having exactly this issue

**Comment by ShaDisNX255** [comment]
> > > Awesome find! But unfortunately it is producing very broken results, so it is unusable on the A72.
> > 
> > 
> > Is it taking the picture and breaking it up into colors? (4 I believe) If this is the case, let me check what other lines it needs because I remember I also had this problem but then I added more lines to camera-feature that fixed it but I'm not exactly sure which one
> 
> Yes, it's having exactly this issue

Alright, let me take a look and hopefully I can find the fix. I'll attempt this all over again and will let you know if I can find the culprit.

**Comment by Rpapaa2** [comment]
And adding from automatic hdr mode from video mode ? :)

I'm using from gcam from saving raw image, but quality is not okay from gcam app.

**Pull request closed without merging**
